/**
 * Sabian symbol data — Marc Edmund Jones (1925) set, 360 entries.
 *
 * Source
 * ──────
 * 348 entries transcribed from the third edition of *The Sabian Symbols
 * in Astrology* by Marc Edmund Jones (Aurora Press, Santa Fe NM, 1993,
 * ISBN 9780943358406, first published 1925) — public domain in the US.
 *
 * The remaining 12 image phrases — degrees 8, 52, 125, 126, 143, 217,
 * 225, 253, 305, 306, 351, 352 — are taken from the canonical Jones
 * (1925) list. Their source pages in the PDF were column-merge garbled
 * by pdftotext extraction; the image text is well-attested in published
 * Jones tabulations, but the interpretation field is left empty pending
 * a clean source.
 *
 * `image` is the iconic picture (e.g. "A flock of wild geese.").
 * `interpretation` is Jones's own "This is a symbol of …" line, trimmed
 * to a single sentence. Empty string when no clean source was available.
 *
 * Indexed by `degree - 1`, where degree 1 = 1° Aries and degree 360 = 30° Pisces.
 */

export interface SabianEntry {
  /** The iconic symbol image. Always ends with a period. */
  image: string
  /**
   * Jones's "This is a symbol of …" gloss as a single sentence.
   * Empty when only the image is known (12 entries).
   */
  interpretation: string
}

export const SABIAN_DATA: readonly SabianEntry[] = [
  { image: 'A woman rises out of water, a seal rises and embraces her.', interpretation: 'completely unconditioned potentiality, as this may be grasped on the practical side of life.' },  //   1 · Aries 1
  { image: 'A comedian entertaining a group.', interpretation: 'the mirror which life holds up to itself recurrently, and so facilitates an everyday understanding of itself.' },  //   2 · Aries 2
  { image: 'A cameo profile of a man in the outline of his country.', interpretation: 'a real breadth of participation in everyday affairs, and of the extent to which every individual tends to epitomize the tradition and culture from which he has emerged.' },  //   3 · Aries 3
  { image: 'Two lovers strolling through a secluded walk.', interpretation: 'the first innocent rounding out of conscious experience, and of an unspoiled assurance of personal potentialities for which no immediate sense of responsibility is necessary.' },  //   4 · Aries 4
  { image: 'A triangle with wings.', interpretation: 'the inviolability of man\'s essential nature throughout every ramification of his experience, as long as he holds to the purity of his original impulses.' },  //   5 · Aries 5
  { image: 'A square brightly lighted on one side.', interpretation: 'experience as the over-all sustainment of any personal or conscious being.' },  //   6 · Aries 6
  { image: 'A man successfully expressing himself in two realms at once.', interpretation: 'a creative division of labor within the self, such as distinguishes human kind from the lower orders of life and enables any individual to participate in the experience of many interpenetrating realms of reality.' },  //   7 · Aries 7
  { image: 'A large hat with streamers flying east.', interpretation: '' },  //   8 · Aries 8
  { image: 'A crystal gazer.', interpretation: 'man\'s capacity for bringing an entire universe within the purview ofhis mind.' },  //   9 · Aries 9
  { image: 'A man teaching new forms for old symbols.', interpretation: 'the continuous and necessary rectification of understanding through direct and everyday experience, such as brings every factor of inner realization into immediate and personal significance.' },  //  10 · Aries 10
  { image: 'The president of the country.', interpretation: 'high ego on the impersonal side, evident in the complete and naive dedication of the individual to some part he chooses to play among his fellows.' },  //  11 · Aries 11
  { image: 'A flock of wild geese.', interpretation: 'the irresistible aspiration and indomitable desire for freedom which represent the real core of personality, and which in everyday affairs are often the sole manifestation of an individual\'s immortal potential.' },  //  12 · Aries 12
  { image: 'An unsuccessful bomb explosion.', interpretation: 'the survival of good through evil intention and effort, and of the infinite capacity of the world to absorb and _nullify the destructive acts of man.' },  //  13 · Aries 13
  { image: 'A serpent coiling neara man andawoman.', interpretation: 'the threefold nature of man, in its aspect of a high competency on the subjective side.' },  //  14 · Aries 14
  { image: 'An Indian weaving a blanket.', interpretation: 'personal fulfillment through a simple excellence of self-expression, and it presents the basic skills of being as a means for bringing all desired things to center in a true self-possession.' },  //  15 · Aries 15
  { image: 'Brownies dancing in the setting sun.', interpretation: 'the essentially friendly relationships which exist between man as a person and the totally impersonal forces of nature.' },  //  16 · Aries 16
  { image: 'Two prim spinsters.', interpretation: 'what ultimately becomes an entirely private sustainment of reality, or a characteristically personal creation of his world in its varying aspects on the part of each participant in its events.' },  //  17 · Aries 17
  { image: 'An empty hammock.', interpretation: 'selfadequacy at its maximum potential for inner reorientation and outer readjustment, and of an utter absoluteness of noncompulsion on man as far as any essential conditioning or self-irrevocability is concerned.' },  //  18 · Aries 18
  { image: 'The magic carpet.', interpretation: 'the periodic expansion of man\'s freedom of spirit and soul through his widely winging interest in potentialities far removed from his normal promise, dramatized here on the side of a vicarious or imaginative self-fulfillment.' },  //  19 · Aries 19
  { image: 'A young girl feeding birds in winter.', interpretation: 'man\'s self-assurance as regained by giving nourishment to forms of life other than his own.' },  //  20 · Aries 20
  { image: 'A pugilist entering the ring.', interpretation: 'a complete lack of personal sensitiveness.' },  //  21 · Aries 21
  { image: 'The gate to the garden of desire.', interpretation: 'man\'s uncompromising faith in the fact of his being, and of his naive optimism as life opens up one or another of its opportunities before him.' },  //  22 · Aries 22
  { image: 'A woman in pastel colors carrying a heavy and valuable but veiled load.', interpretation: 'the soul\'s basic anchorage in the privacy of its own functioning, and of the centering of real personality in the elements of its own particular genius.' },  //  23 · Aries 23
  { image: 'An open window and a net curtain blowing into a cornucopia.', interpretation: 'the mutual prodigality of man and his world whenever he retains his uninhibited enthusiasm and so welcomes every varying and recurrent Opportunity opening up before him.' },  //  24 · Aries 24
  { image: 'A double promise.', interpretation: 'man\'s stark resourcefulness on the side of everyday experience.' },  //  25 · Aries 25
  { image: 'A man possessed of more gifts than he can hold.', interpretation: 'exceptional personal endowment on the side of social capacity and of an individual\'s ever-potential value to his fellows, here marked by an abnormal spread of interest and a tendency to attempt all things.' },  //  26 · Aries 26
  { image: 'Lost opportunity regained in the imagination.', interpretation: 'the psychological maturity of man on the practical side of lite, and of the all-important and creative fluidity of character which makes him an immortal being.' },  //  27 · Aries 27
  { image: 'A large disappointed audience.', interpretation: 'the transiency of the rewards in a life taken too literally and narrowly in its more superficial terms.' },  //  28 · Aries 28
  { image: 'A celestial choir singing.', interpretation: 'man\'s capacity to make himself an immortal instrument for the enduring visions and aspirations which have created and now hallow the world in which he lives.' },  //  29 · Aries 29
  { image: 'A duck pond and its brood.', interpretation: 'the eternal fitness of things, provided the individual take the fullest advantage of the cosmic ordering.' },  //  30 · Aries 30
  { image: 'A clear mountain stream.', interpretation: 'the individual spirit in its irrepressibility, and of the purity and excellence of its real sources of strength.' },  //  31 · Taurus 1
  { image: 'An electrical storm.', interpretation: 'man\'s real power for making an effective impact on events, dramatized at each moment of issue and crisis by the completeness of his inward self-mobilization.' },  //  32 · Taurus 2
  { image: 'Steps up to a lawn blooming with clover.', interpretation: 'the indomitable outreaching of the human spirit on the side of a possible and profitable co-operation with the natural universe, and of man\'s intuition of divine reality as he entrenches himself in beauty and order.' },  //  33 · Taurus 3
  { image: 'The rainbow\'s pot of gold.', interpretation: 'the true incentives of an outer and physical world, and of the rewards which are guaranteed by an eternal covenant between the least of individuality and the universal matrix of life itself.' },  //  34 · Taurus 4
  { image: 'A widow at an open grave.', interpretation: 'the impermanence of physical things whenever man permits reality to come to center in the static representation, and thus neglects the creative contribution through which he has responsibility for the larger whole.' },  //  35 · Taurus 5
  { image: 'A bridge being built across a gorge.', interpretation: 'the conquest of natural difficulties by conscious means, and of any individual\'s essential independence of nature\'s accidents or inconveniences.' },  //  36 · Taurus 6
  { image: 'A woman of Samaria.', interpretation: 'the unimpeachable divinity which characterizes man\'s nature at root, represented here by his instinct for higher things as he yet plumbs all experience to the depths and welcomes life almost indiscriminately into the uttermost inner reaches of his being.' },  //  37 · Taurus 7
  { image: 'A sleigh without snow.', interpretation: 'the magic which man always may summon to his assistance in facing the problems of everyday living.' },  //  38 · Taurus 8
  { image: 'A Christmas tree decorated.', interpretation: 'a self-renewal through a sharing with others, or a remaking of ties and a regathering of visions through the recurrent birth of a world spirit.' },  //  39 · Taurus 9
  { image: 'A Red Cross nurse.', interpretation: 'human service on the ideal or spiritual side and it emphasizes the greatest of all roads to self-realization.' },  //  40 · Taurus 10
  { image: 'A woman sprinkling flowers.', interpretation: 'the soul\'s determination to give constant and tangible manifestation of its creative powers, and of its eagerness to pour itself into every potentiality of living.' },  //  41 · Taurus 11
  { image: 'Window-shoppers.', interpretation: 'human imagination as the real corrective for man\'s experience, enabling each individual to know in advance whether the choices he will make are in line with his desires.' },  //  42 · Taurus 12
  { image: 'A man handling baggage.', interpretation: 'the joy in effort put forth on the practical or everyday side of life, and of the adjustment by which the human individual is able to make his niche for himself in each available sphere of activity.' },  //  43 · Taurus 13
  { image: 'Shellfish groping and children playing.', interpretation: 'the self-sufficiency of existence on each separate level of being, thus preserving the lower orders and facilitating the progressive development of higher ones.' },  //  44 · Taurus 14
  { image: 'A man muffled up, with a rakish silk hat.', interpretation: 'absolute self-integrity at a simple extreme of selfconsciousness, or of the human spirit in its inherent supremacy over all possible limitations or embarrassments.' },  //  45 · Taurus 15
  { image: 'An old man attempting vainly to reveal the Mysteries.', interpretation: 'the need to share whatever may be the ultimate substance of selfhood, as here brought to a personal realization on the intellectual side.' },  //  46 · Taurus 16
  { image: 'A battle between the swords and the torches.', interpretation: 'the eternal struggle between the practical necessities or transient competitions of life on the one hand and the motives and meanings which give them direction and order on the other, as here emphasized on the world stage.' },  //  47 · Taurus 17
  { image: 'A woman holding a bag out of awindow.', interpretation: 'the soul\'s high ministry of service to every purpose and function of living, and of the individual\'s self-fulfillment as he furthers the over-all ends of men in general.' },  //  48 · Taurus 18
  { image: 'A newly formed continent.', interpretation: 'the raw substance of existence, and it suggests that experience may shape its own ground in full conformity with its desires.' },  //  49 · Taurus 19
  { image: 'Wind clouds and haste.', interpretation: 'the transiency which characterizes life for the average individual, and of the instability which results from the disinclination of most people to give very much of themselves to their experience.' },  //  50 · Taurus 20
  { image: 'A finger pointing in an open book.', interpretation: 'the rectification of experience on the side of ends and meanings, and of the fine discrimination of which man is capable.' },  //  51 · Taurus 21
  { image: 'A white dove flying over troubled waters.', interpretation: '' },  //  52 · Taurus 22
  { image: 'A jewelry shop.', interpretation: 'the practical values of everyday living, and of the personal display by which man may cherish the rewards of his effort and so seek to give them an effective durability.' },  //  53 · Taurus 23
  { image: 'A mounted Indian with scalp locks.', interpretation: 'pride in personal prowess, and it suggests an exceptional capacity for gaining and administering authority among men.' },  //  54 · Taurus 24
  { image: 'A large well-kept public park.', interpretation: 'the everyday integrity of society at large, and of the community divisions of labor through which each person gains the resources for well-being and self-enjoyment which obviously he could never create for himself through his own isolated efforts.' },  //  55 · Taurus 25
  { image: 'A Spaniard serenading his senorita.', interpretation: 'man\'s unlimited capacity for self-establishment and for finding everything he desires immediately at hand, as here given emphasis on the ideal side.' },  //  56 · Taurus 26
  { image: 'A squaw selling beads.', interpretation: 'the soul\'s fundamental disinterest in everyday superficialities, and of its characteristic anchorage in an inner reality.' },  //  57 · Taurus 27
  { image: 'A woman pursued by mature romance.', interpretation: 'the eternal promise underlying all objective existence, since the fullness of life is ageless and the human spirit immortal in its functioning.' },  //  58 · Taurus 28
  { image: 'Two cobblers working at a table.', interpretation: 'the co-operative wisdom by which men make their world their own, solving all its special problems through the simple communion of functions performed in a genuine division of labor.' },  //  59 · Taurus 29
  { image: 'A peacock parading on an ancient lawn.', interpretation: 'the proper dignification which can be given to superficial excellencies, individual beyond his and of the capacity or momentary worth as he elevation is able to of the exhibit ouasuNitefohgnnnseugirqshcn.' },  //  60 · Taurus 30
  { image: 'A glass-bottomed boat in still water.', interpretation: 'man\'s alertness to every ramification of experience open to him, and of the necessity that he take definite action on his own account if he is to capitalize on any particular opportunity.' },  //  61 · Gemini 1
  { image: 'Santa Claus filling stockings furtively.', interpretation: 'the illimitable source of everything ever needed for life and experience, emphasized on the practical side of everyday rewards and individual compensations.' },  //  62 · Gemini 2
  { image: 'The garden of the Tuileries.', interpretation: 'the self-confidence and authority which come to man through social position and wealth, and of his ability to bring all his capabilities to some graceful and exquisite self-expression.' },  //  63 · Gemini 3
  { image: 'Holly and mistletoe.', interpretation: 'the maximum possible encouragement of human personality on the inner or subjective side, or of life\'s continual stimulus to every resource of imagination and spiritual appreciation.' },  //  64 · Gemini 4
  { image: 'A radical magazine.', interpretation: 'the necessary element of change in human affairs, and of the extent to which the remote or the nonpossessed and entirely potential will have its full and functioning part in any immediate reality with which an individual may be seeking to come to terms.' },  //  65 · Gemini 5
  { image: 'Drilling for oil.', interpretation: 'man\'s indomitable efforts to discover every last resource of the world in which he finds himself, and of his desire to endow his experience with every possible enhancement on the physical side of things.' },  //  66 · Gemini 6
  { image: 'An old-fashioned well.', interpretation: 'the unimpeachable source of life on the side of personal self-renewal and simple organic integrity.' },  //  67 · Gemini 7
  { image: 'An industrial strike.', interpretation: 'the necessity that man act in his own interest whenever his general situation fails to provide him with the creative outlet he needs, or proves inadequate for his relations with his fellows.' },  //  68 · Gemini 8
  { image: 'A quiver filled with arrows.', interpretation: 'extreme alertness to the interests and needs of selfhood, and of high competency in pursuing any and all practical ends in view.' },  //  69 · Gemini 9
  { image: 'An airplane falling.', interpretation: 'the capacity of man to plunge into experience with a complete disregard of consequences, or to act in full independence of those sustainments which his fellows have accepted as limitation.' },  //  70 · Gemini 10
  { image: 'A new path of realism in experience.', interpretation: 'the enlarged understanding which comes from a personal and immediate participation in the affairs of an everyday world, and of the continuing rewards which result from trying one and another way of doing things.' },  //  71 · Gemini 11
  { image: 'A Topsy saucily asserting herself.', interpretation: 'the balance which every individual must maintain between the compulsions of the social milieu on which his wellbeing depends and the necessity that he exercise his fledgling wings on every possible occasion.' },  //  72 · Gemini 12
  { image: 'A great musician at his piano.', interpretation: 'individual artistry as the property of all, with its expression both its strength and the means whereby others are encouraged to like accomplishment.' },  //  73 · Gemini 13
  { image: 'A conversation by telepathy.', interpretation: 'the transcendent level on which human experience has its truest focus, here at the extreme of personal realization.' },  //  74 · Gemini 14
  { image: 'Two Dutch children talking.', interpretation: 'the creative interest of man in the broad range of potentialities on which he may draw.' },  //  75 · Gemini 15
  { image: 'A woman suffragist haranguing.', interpretation: 'the soul\'s demand for a full participation in the responsibilities of human society, and of the realization that the values of life are maintained only as there is a mutual give-and-take in respect to every real difference in point of view.' },  //  76 · Gemini 16
  { image: 'The head of health dissolved into the head of mentality.', interpretation: 'man\'s achievement on the level of spiritual or eternal fellowship with his kind, here emphassized subjectively as a focus of selfhood in conscious self-awareness and as a capacity to live the lives of all men in imagination and appreciation.' },  //  77 · Gemini 17
  { image: 'Two Chinese men talking Chinese.', interpretation: 'an everyday exclusiveness on the intellectual side of experience, the individual strengthened not as much by actual distinctiveness as by a continual co-operation with fellow enthusiasts in various special areas of interest.' },  //  78 · Gemini 18
  { image: 'A large archaic volume.', interpretation: 'the ultimate indestructibility of experience, so that any path once traversed may be taken again with a greater ease and a broader self-discovery.' },  //  79 · Gemini 19
  { image: 'A cafeteria.', interpretation: 'the facility with which men organize their own special experience for the benefit of the community at large.' },  //  80 · Gemini 20
  { image: 'A labor demonstration.', interpretation: 'man\'s unimpeachably universal spirit, and of his realization that the lines of property and private rights which he finds entrenched all around him are limitations without validity except as they constitute a social stewardship.' },  //  81 · Gemini 21
  { image: 'A barn dance.', interpretation: 'complete selffulfillment through the established or normal activities of the community at large, and of a consummation of self by the broadest possible participation in the divisions of labor which constitute a human society.' },  //  82 · Gemini 22
  { image: 'Three fledglings in a nest high ina tree.', interpretation: 'potentiality caught and held through an initial and effective appreciation, here dramatized by man\'s capacity for giving each nascent possibility of character a chance to prove itself.' },  //  83 · Gemini 23
  { image: 'Children skating on ice.', interpretation: 'the persisting imminence of adventure in experience, and of the constant danger to self in failing to sustain or order the complex of things as they are.' },  //  84 · Gemini 24
  { image: 'A man trimming palms.', interpretation: 'the pride in effort by which man seeks to leave his immortal stamp on the world around him.' },  //  85 · Gemini 25
  { image: 'Winter frost in the woods.', interpretation: 'the cosmic significance in any momentary cancellation of the more immediate interests and private concerns, and the emphasis is on the supremacy of the needs and powers of nature over the aspirations and conveniences of man.' },  //  86 · Gemini 26
  { image: 'A gypsy coming out of the forest.', interpretation: 'human enthusiasm or of self-consciousness mobilized in a freshness or naiveté of self-realization and dramatized by an irresistible desire for success and recognition in an everyday world.' },  //  87 · Gemini 27
  { image: 'A man declared bankrupt.', interpretation: 'the eternal individuality of the human spirit, able to enter new paths of opportunity and thereupon achieve a further selfrefinement whenever its particular involvements in everyday affairs have come to some point of futility.' },  //  88 · Gemini 28
  { image: 'The first mockingbird in spring.', interpretation: 'the contribution of aesthetic experience to the strengthening of self at core, given emphasis by the skill in imitation through which any vicarious participation in life is enhanced.' },  //  89 · Gemini 29
  { image: 'Bathing beauties.', interpretation: 'human excellence on the side of purely natural endowment, and of the soul as wholly inadequate except as it is able to meet some need of everyday experience with the elements inherent in its make-up and so free from any or all responsibility to anything other than itself.' },  //  90 · Gemini 30
  { image: 'A furled and an unfurled flag displayed from a vessel.', interpretation: 'the extremes to which an individual will go in the practical allegiances with which he meets the various situations in life, and of his capacity to compromise or reverse any stand he may take whenever this suits his ultimate ends.' },  //  91 · Cancer 1
  { image: 'A man suspended over a vast level place.', interpretation: 'man\'s capacity for an illimitable overview of his experience in advance of his involvement in its details, and of the infinite ramification of possibilities he is able to uncove1 in the world he seeks to make his own.' },  //  92 · Cancer 2
  { image: 'A man all bundled up in fur leading a shaggy deer.', interpretation: 'the pioneer or trail-blazing instinct in the human heart, and of the self\'s insistent determination to strengthen itself in its own highly individual roots.' },  //  93 · Cancer 3
  { image: 'A cat arguing with a mouse.', interpretation: 'man\'s necessary establishment of a set in mind or realization as a preliminary to any entrance into personal experience, and of his tendency to enjoy the preparatory more than the consummatory phases of his participation in reality.' },  //  94 · Cancer 4
  { image: 'An automobile wrecked by a train.', interpretation: 'the irresistible power of completion inherent in the very make-up of man\'s world whenever a sequence of events once is set in motion, as is evident continually on the objective side of things.' },  //  95 · Cancer 5
  { image: 'Game birds feathering their nests.', interpretation: 'the unlimited degree to which the spirit of man may develop and preserve its initiative by utilizing the natural course of things in the world at large, and of the satisfaction anyone may know through his conscious participation in a group destiny.' },  //  96 · Cancer 6
  { image: 'Two fairies on a moonlit night.', interpretation: 'nature\'s illimitable potentialities on the side of the release she offers man from his physical or psychological involvement, and of the necessity that he achieve some measure of lightness in self-expression as a balance for the strain of everyday existence.' },  //  97 · Cancer 7
  { image: 'Rabbits dressed in clothes and on parade.', interpretation: 'the upward reach of consciousness towards spirit, or of the necessity in all worth-while experience that events in some fashion make their continual and stimulating contribution to whatever values the self may be building into its own nature.' },  //  98 · Cancer 8
  { image: 'A tiny nude miss reaching in the water for a fish.', interpretation: 'the eternal and unsullied freshness of soul as it enters every new experience with an unabated enthusiasm and thereby both substantiates its divine estate and brings enduring significance to whatever it may touch.' },  //  99 · Cancer 9
  { image: 'A large diamond not completely cut.', interpretation: 'man\'s basic self-justification on the cultural or intellectual side, and of the complete dependence of the world around him on his arts and skills for any values that may be built or sustained in its eternal promise.' },  // 100 · Cancer 10
  { image: 'A clown making grimaces.', interpretation: 'the continual self-rehearsal by which the everyday personality of man is able to sustain its particular characteristics, and of the tentative side of experience through which the uncertainties of life can be dramatized for acceptance or rejection without incurring any penalties.' },  // 101 · Cancer 11
  { image: 'A Chinese woman nursing a baby with a message.', interpretation: 'the wide ramification in experience by which man achieves his greater opportunities, emphasized on the wholly personal side as he is able to include the far-flung capabilities of the race itself in his own individual complex of talents and skills.' },  // 102 · Cancer 12
  { image: 'One hand slightly flexed with a very prominent thumb.', interpretation: 'that belief in his inherent supremacy over all other orders of nature by which man is characterized most fundamentally, dramatized by his quite normal confidence in his ability to deal with every eventuality of dayby-day activity and relationship.' },  // 103 · Cancer 13
  { image: 'A very old man facing a vast dark space to the northeast.', interpretation: 'the immeasurable reaches of past experience as a strengthening of the human spirit for its immediate destiny, and of the eternal rebirth through which man may discover that present aspiration and future achievement are without the slightest limitation in any terms of events to come.' },  // 104 · Cancer 14
  { image: 'A group of people who have overeaten and enjoyed it.', interpretation: 'the inescapable richness of life in any normal manifestation of itself, here given emphasis on the side of the rewards which come to man as a result of his own efforts.' },  // 105 · Cancer 15
  { image: 'A man before a square with a manuscript scroll before him.', interpretation: 'intellectual experience as primarily an exercise in self-competency, or of life as a neverending adjustment of practical realities to their ideal potentials.' },  // 106 · Cancer 16
  { image: 'The germ grows into knowledge and life.', interpretation: 'the irresistible determination of living substance to press forward indefinitely and uncompromisingly in the expansion and refinement of its own special genius and identity, and thus to establish every possible phase of self-existence in more eternal lineaments.' },  // 107 · Cancer 17
  { image: '4 hen scratching for her chicks.', interpretation: 'the maximum protection which life at large will provide for the individual in general, here given emphasis on the personal side.' },  // 108 · Cancer 18
  { image: 'A priest performing a marriage ceremony.', interpretation: 'the spiritual stewardship of man as expressed in his conscious concern for the integrity of human society and for the everyday institutions through which all racial ideals must have their continued embodiment.' },  // 109 · Cancer 19
  { image: 'Gondoliers in a serenade.', interpretation: 'the ever-exuberant music of life itself, and is an emphasis on experience as a symphony of co-operative relationships.' },  // 110 · Cancer 20
  { image: 'A prima donna singing.', interpretation: 'an inevitable culmination for individual opportunity, and of an enduring contribution of skill and talent to whatever may entertain the soul\'s recurrent and constant rediscovery of itself.' },  // 111 · Cancer 21
  { image: 'A woman awaiting a sailboat.', interpretation: 'the creative poise and quiet range of perspective which give real power to the human soul, endowing it with its gift for sustained interest in the present situation and its constructive attitude towards each ramifying potentiality of things to be.' },  // 112 · Cancer 22
  { image: 'Meeting of a literary society.', interpretation: 'man\'s resourcefulness in developing new areas of experience on the imaginative side, and of his genius for widening his interests and stimulating everybody to broader ideals and more rewarding goals in everyday living.' },  // 113 · Cancer 23
  { image: 'A woman and two men ona bit of sunlit land facing south.', interpretation: 'the soul\'s necessary decisiveness in the basic allegiances of life, here emphasized in the terms of practical or everyday relations.' },  // 114 · Cancer 24
  { image: 'A dark shadow or mantle thrown suddenly over the right shoulder.', interpretation: 'the irrevocability of man\'s obligation to the reality of which he is a part, with the emphasis on his capacities of leadership as a revelation of racial stewardship on the more personal or spiritual side.' },  // 115 · Cancer 25
  { image: 'Contentment and happiness in luxury, people reading on davenports.', interpretation: 'a pure mastery of experience in the potentials its outer aspect, of all being in a and of a full capitalization on personal and ultimately immortal realization.' },  // 116 · Cancer 26
  { image: 'A storm inacanyon.', interpretation: 'a pyramiding reality on the side of external circumstances, or of violence and terror as divine in their capacity for lifting man out of his aplomb and demanding some manifestation of his inner ideals and enduring values.' },  // 117 · Cancer 27
  { image: 'A modern Pocahontas.', interpretation: 'effective co-operation between various phases of human culture, such as those which have become crystallized in a faithfulness to the special values they have held intact and those which provide the new potentials of a genuine frontier spirit.' },  // 118 · Cancer 28
  { image: 'A Muse weighing twins.', interpretation: 'man\'s continual if not always evident relationship with the over-reality in which he lives and moves and has his being, here given an emphasis on the side of inner reconciliations.' },  // 119 · Cancer 29
  { image: 'A Daughter of the American Revolution.', interpretation: 'the enduring background in human relations as essentially dependent on an established tradition, and of a willingness to maintain it through a sharp rejection of any modifying influence of unsympathetic times or events.' },  // 120 · Cancer 30
  { image: 'A case of apoplexy.', interpretation: 'an overwhelming potentiality, and of an ever-pressing necessity for genuine self-establishment and personal stability.' },  // 121 · Leo 1
  { image: 'An epidemic of mumps.', interpretation: 'personal capacities wholly out of hand, and of the momentary appeal of escapist ideas whenever the self fails to remain alive to its own immediate needs or ultimate interests.' },  // 122 · Leo 2
  { image: 'A woman having her hair bobbed.', interpretation: 'human independence carried to a point of extreme self examination, here emphasized in a desire for greater participation in the momentary trends and heightened values of the social milieu.' },  // 123 · Leo 3
  { image: 'A man formally dressed and a deer with its horns folded.', interpretation: 'self-assertion at a point of effective impact on the world, dramatized here on the side of an established and everyday reality.' },  // 124 · Leo 4
  { image: 'Rock formations tower over a deep canyon.', interpretation: '' },  // 125 · Leo 5
  { image: 'An old fashioned conservative woman is confronted by an up-to-date girl.', interpretation: '' },  // 126 · Leo 6
  { image: 'The constellations in the sky.', interpretation: 'the infinite regression in all universal reality, not as a fact of some unreachable end in knowledge but rather as a demonstration that any abandonment of the known for the sake of the unknown is fruitless.' },  // 127 · Leo 7
  { image: 'A Bolshevik propagandist.', interpretation: 'the indomitable expectation of the human spirit as it gathers strength from the innermost reaches of man\'s own or enduring nature, here emphasized by the recurrent battles over social and political concepts.' },  // 128 · Leo 8
  { image: 'Glass blowers.', interpretation: 'man\'s inexhaustibly creative skill of hand and genius of self-application, and of his inherent urge to perform the tasks to be done and to have justification in the ideals to which he would give expression.' },  // 129 · Leo 9
  { image: 'Early morning dew.', interpretation: 'the eternal refreshment which comes to the individual with every recurrent cycle of his experience, and of nature\'s continual endorsement of his aims or benediction on his efforts.' },  // 130 · Leo 10
  { image: 'Children on a swing in a huge oak tree.', interpretation: 'satisfaction in the normal exercise of selfhood, and of a new realization of the high dependability exhibited by man\'s physical and social sustainments.' },  // 131 · Leo 11
  { image: 'An evening lawn party.', interpretation: 'the common enhancement of individual experience on the side of its more superficial or everyday gratifications, and of the inherent normality through which man shares the fruits of his personal accomplishment with his intimates and neighbors at every opportunity.' },  // 132 · Leo 12
  { image: 'An old sca captain rocking.', interpretation: 'man\'s great love for reliving his experiences in memory, and of his gift for achieving a mastery in advance of whatever new situations he may face by bringing all the ramifying relationships to a focus in a personal and competent grasp of their more pertinent potentialities.' },  // 133 · Leo 13
  { image: 'The human soul awaiting opportunity for expression.', interpretation: 'life\'s normal expectation on the personal or subjective side, and of the totally unconditioned potential of self at its point of entrance into each new complex of activity with its fellows.' },  // 134 · Leo 14
  { image: 'A pageant.', interpretation: 'man\'s constant delight in exhibiting the fruits of his achievement, and of a naiveté dramatized in the world of everyday through a very human pride in common works and co-operative accomplishment.' },  // 135 · Leo 15
  { image: 'Sunshine just after a storm.', interpretation: 'personal stability through man\'s recuperative powers, emphasized in terms of his psychological or inner orientation.' },  // 136 · Leo 16
  { image: 'A nonvested church choir.', interpretation: 'the inviolability of experience as dramatized for each individual through his participation in the broader or community functions of life.' },  // 137 · Leo 17
  { image: 'A teacher of chemistry.', interpretation: 'the human mind\'s illimitable power for penetrating into the deeper mysteries of an everyday world, and of the growing ambition of man to gain an effective control over all the processes of nature.' },  // 138 · Leo 18
  { image: 'A houseboat party.', interpretation: 'creative relaxation as a prelude to effective effort, and of man\'s normal capacity for achievement through an everyday rehearsal of co-operative relationships with his fellows.' },  // 139 · Leo 19
  { image: 'The Zuni sun worshipers.', interpretation: 'man\'s recognition of higher and natural forces from which he receives his life and strength, emphasized here in his everyday ritualization of his loyalties and in his self-buttressing through a preservation of older values in any evolution of new ones.' },  // 140 · Leo 20
  { image: 'Chickens intoxicated.', interpretation: 'the inevitable distress of the human soul whenever it seeks stimulation from elements essentially alien to its own nature, dramatized in the reversed symbolism by the futility of a dependence on physical agency for spiritual results.' },  // 141 · Leo 21
  { image: 'A carrier pigeon.', interpretation: 'the unlimited service of life at large to the special requirements of an individual\'s intelligence or understanding.' },  // 142 · Leo 22
  { image: 'A bareback rider in a circus.', interpretation: '' },  // 143 · Leo 23
  { image: 'An untidy, unkempt man.', interpretation: 'the complete self-obsession which human individuality may exhibit, emphasized here on the side of an insensitiveness to every exaction or reward of the world.' },  // 144 · Leo 24
  { image: 'A large camel crossing the desert.', interpretation: 'man\'s capacity to overcome the handicaps imposed on him by the normal limitations of the world in which he elects to function, and of his underlying and basically inexhaustible endurance.' },  // 145 · Leo 25
  { image: 'A rainbow.', interpretation: 'the over-all realization which comes to man for his guidance whenever he strives to reach his goals of a more enduring sort.' },  // 146 · Leo 26
  { image: 'Daybreak.', interpretation: 'the cycles of change as an ultimate assurance to the human heart, with an emphasis on reason as the means by which man knows the nature of his own continuance.' },  // 147 · Leo 27
  { image: 'Many little birds on the limb of a large tree.', interpretation: 'the transcendence of the lesser things in life by a continual expansion of higher considerations, or of the individual\'s ability in a crisis to center his attention on the enduring orientations through which he gains his own assurance.' },  // 148 · Leo 28
  { image: 'A mermaid.', interpretation: 'humanity\'s insatiable appetite for experience on the side of psychological selfassurance, and of the nascent eagerness of the soul for a private and personal participation in every possible facet of self-fulfillment.' },  // 149 · Leo 29
  { image: 'An unsealed letter.', interpretation: 'the spiritual integrity of all things in and of themselves, dramatized here by the remarkable extent to which reliance may be placed on the discretion of others in even the most trivial details of dayby-day living.' },  // 150 · Leo 30
  { image: 'A man\'s head.', interpretation: 'full maturity in human estate, with an emphasis on the personal integrity which represents in general what all men are asked to be in particular.' },  // 151 · Virgo 1
  { image: 'A large white cross upraised.', interpretation: 'the conscious stewardship through which man sustains his more enduring values, here emphasized by an uncompromising testimony to his deeper allegiances.' },  // 152 · Virgo 2
  { image: 'Two angels bringing protection.', interpretation: 'the absolute certainty which any individual may develop in the terms of his conscious faith, and of the power in human character which becomes the hallmark of his spiritual orientation.' },  // 153 · Virgo 3
  { image: 'A colored child playing with white children.', interpretation: 'the actual illimitability of human relationships, dramatized here in the more personal and wholly specialized environment of everyday affairs.' },  // 154 · Virgo 4
  { image: 'A man dreaming of fairies.', interpretation: 'the imaginative resources of life as manifest in the folklore of the race, and of man\'s ability to use the coin of his inner and eternal experience with a practical wisdom and insight.' },  // 155 · Virgo 5
  { image: 'A merry-go-round.', interpretation: 'a cyclic and necessary intensification of any personal being, as emphasized on the side of normal or everyday experience.' },  // 156 · Virgo 6
  { image: 'A harem.', interpretation: 'the withdrawal from reality in one aspect as a means for regrasping it in another, here dramatized by an acceptance of regimentation as a species of insulation against life\'s demand for some more dynamic manifestation of the self.' },  // 157 · Virgo 7
  { image: 'First dancing instruction.', interpretation: 'the self-perfecting required for the many different forms of man\'s participation in the experience of his fellows, illustrated here in a potential excellence of special skill.' },  // 158 · Virgo 8
  { image: 'A man making a futurist drawing.', interpretation: 'the originality an individual must show in any true assertion of himself, and of the importance of the aesthetic or more spiritual areas of his experience.' },  // 159 · Virgo 9
  { image: 'Two heads looking out and beyond the shadows.', interpretation: 'man\'s transcendental powers of comprehension, emphasized here in his ability to reduce all knowledge to exact and efficient formulas.' },  // 160 · Virgo 10
  { image: 'A boy molded in his mother\'s aspiration for him.', interpretation: 'the immortality of man as dramatized in his physical heredity, or in a succession of tangible achievements and possessions down through a family line.' },  // 161 · Virgo 11
  { image: 'A bride with her veil snatched away.', interpretation: 'life\'s demand that man continue at all times to prove himself in full accordance with the claims he has made for himself, emphasized here on the side of his everyday relationships with his fellows.' },  // 162 · Virgo 12
  { image: 'A strong hand supplanting political hysteria.', interpretation: 'the real weight of human personality as emphasized here by the direct intervention of outstanding individuals in the affairs of their follows.' },  // 163 · Virgo 13
  { image: 'A family tree.', interpretation: 'the ever-effective dynamic with which an established tradition endows mankind, dramatized here by the extent to which an individual will live the lives of his forebears or accept the guidance stemming from them through their spiritual presence in his blood.' },  // 164 · Virgo 14
  { image: 'An ornamental handkerchief.', interpretation: 'man\'s self-quickening desire for allegiance to a reality higher or finer than himself, evident on the side of his aesthetic instincts.' },  // 165 · Virgo 15
  { image: 'An orangutan.', interpretation: 'the primitive power which the processes of evolution have brought into leash with the development of mankind, and which each person must refine for his own use in meeting the demands of higher life.' },  // 166 · Virgo 16
  { image: 'A volcano in eruption.', interpretation: 'that constant expansion of self and nature which constitutes reality in its most fundamental terms, emphasized here on the side of physical force and the blind urge of life to continue to be.' },  // 167 · Virgo 17
  { image: 'An ouja board.', interpretation: 'the completeness with which man is able to see his experience both steadily and whole, dramatized here by the planchette as representative of effective anticipation or a true rational divination.' },  // 168 · Virgo 18
  { image: 'A swimming race.', interpretation: 'the utter impartiality of existence in any larger dimension, and of the stimulus of direct competition whenever an individual seeks to perfect or enjoy some one of the special skills comprising his individuality.' },  // 169 · Virgo 19
  { image: 'An automobile caravan.', interpretation: 'nature\'s prodigality as revealed through man\'s genius for multiplying the facilities of modern life, and for pyramiding the expectancies which will interest an enlightened individual.' },  // 170 · Virgo 20
  { image: 'A girls\' basketball team.', interpretation: 'the integrated divisions of labor by which any higher reality is manifest in everyday terms, and of the opportunity which the wide variations of modern life have provided for individual specialization and personal refinement.' },  // 171 · Virgo 21
  { image: 'A royal coat of arms.', interpretation: 'the eternal authority implicit in the very fact of existence, and of the consequent dignification of experience through the laws and customs by which man organizes the conduct of his own affairs.' },  // 172 · Virgo 22
  { image: 'An animal trainer.', interpretation: 'the organic integrity of the world at large, evident here in man\'s gift for using all its interweaving relationships to impose his ideas and desires on lesser forms of life.' },  // 173 · Virgo 23
  { image: 'Mary and her white lamb.', interpretation: 'the self-adequacy of experience on the inner or subjective side, or of that fullness of life which comes through a cherishing of young ideas.' },  // 174 · Virgo 24
  { image: 'A flag at half-mast.', interpretation: 'the inevitable judgment which life must pronounce on itself, and of the sure rewards that stand ready for whatever proves of worth in the course of effort.' },  // 175 · Virgo 25
  { image: 'A boy withacenser.', interpretation: 'individual initiative as a basic dynamic in the universal scheme of things, and it reveals itself most simply in man\'s positive and necessarily self-seeking outreach to the world he would claim for himself.' },  // 176 · Virgo 26
  { image: 'Grande dames at tea.', interpretation: 'life\'s maturity as a threshold of new discovery rather than as any canceling out of personal reality, and it emphasizes the fact that cach individual may pass on what he has gained and thereby have an effective continuance of himself through others.' },  // 177 · Virgo 27
  { image: 'A bald-headed man.', interpretation: 'a simple satisfaction in the inner rather than outer manifestations of reality, and of the challenge to any purely personal attainment to become more than a visible proof of the special excellency.' },  // 178 · Virgo 28
  { image: 'A man gaining secret knowledge from a paper he ts reading.', interpretation: 'the world\'s conservatism, and of the refusal of nature to surrender any part of her heritage unnecessarily.' },  // 179 · Virgo 29
  { image: 'A false call unheard in attention to immediate service.', interpretation: 'human responsibility as an immortality of the soul, and of a way of living which has achieved an absoluteness of attitude or understanding and is able in consequence to dramatize a high personal competency in everyday problem solving.' },  // 180 · Virgo 30
  { image: 'A butterfly made perfect by a dart through it.', interpretation: 'completely unconditioned potentiality, as this may be grasped on the imaginative side of life.' },  // 181 · Libra 1
  { image: 'The light of the sixth race transmuted to the seventh.', interpretation: 'the mirror which history provides for mankind, so that each new generation may see itself reflected in its own past and therefore may be challenged to its real future.' },  // 182 · Libra 2
  { image: 'The dawn of a new day, everything changed.', interpretation: 'the illimitable potentialities to be found when it comes to any personal participation in everyday affairs, and of the thoroughness with which each individual remains the recurrent expression of his own self-consistencies. There is here the necessity for an ultimate self-dependence, and the consequent need to blaze a path of special recognition for each particular characteristic of selfhood.' },  // 183 · Libra 3
  { image: 'A group around a campfire.', interpretation: 'an initial or uncritical consummation of group experience, and of the totally unconditioned capacity of each individual to associate himself with his kind without exaction or inhibition.' },  // 184 · Libra 4
  { image: 'A man teaching the true inner knowledge.', interpretation: 'the inviolability of all genuine inspiration, and of the opportunity offered every individual to reach out to his fellows through his participation with them in everyday experience, and thereupon to communicate his deeper insights to them through common responsibilities.' },  // 185 · Libra 5
  { image: 'The ideals of a man abundantly crystallized.', interpretation: 'experience as the practical or everyday substantiation of inner insight and conscious understanding.' },  // 186 · Libra 6
  { image: 'A woman feeding chickens and protecting them from the hawks.', interpretation: 'the creative division of labor between the functions of man and nature, and of the dual constitution of the soul in its responsibilities of conservation on the one hand and of development on the other.' },  // 187 · Libra 7
  { image: 'A blazing fireplace in a deserted home.', interpretation: 'naive reality, or of the basic law of the cosmos whereby all things tend to continue steadily in their accustomed function.' },  // 188 · Libra 8
  { image: 'Three old masters hanging in an art gallery.', interpretation: 'man\'s capacity for embracing a universal reality within his own personal experience.' },  // 189 · Libra 9
  { image: 'A canoe approaching safety through dangerous waters.', interpretation: 'the necessary validation of all experience through an acceptance of risk, and of the refinement of personal skills through a direct contact with the recurrent exigencies of everyday living.' },  // 190 · Libra 10
  { image: 'A professor peering over his glasses.', interpretation: 'high ego on the personal side, or of the naive selfconfidence by which an individual is enabled to continue the role of superiority he has elected to play among his fellows.' },  // 191 · Libra 11
  { image: 'Miners emerging from a mine.', interpretation: 'the irresistible curiosity and indomitable self-confidence which represent the real strength of personality, and which in everyday affairs are sometimes the sole manifestation of an individual\'s broader potentials.' },  // 192 · Libra 12
  { image: 'Children blowing soap bubbles.', interpretation: 'man\'s reassurance through the presence of the beautiful and the good in every least promising form of human relationship.' },  // 193 · Libra 13
  { image: 'A noon siesta.', interpretation: 'man\'s basic competency, dramatized on the objective side as he is able to organize his responsibilities and withdraw his attention for a moment of inner reorientation.' },  // 194 · Libra 14
  { image: 'Circular paths.', interpretation: 'subjective fulfillment through a thoroughness of participation in experience, here dramatized by every individual\'s gift for remaining true to himself at center.' },  // 195 · Libra 15
  { image: 'A boat landing washed away.', interpretation: 'the superficially unfriendly relations which exist between man as a person and the totally impersonal forces of nature.' },  // 196 · Libra 16
  { image: 'A retired sea captain.', interpretation: 'what ultimately must be an entirely personal enjoyment of reality, cr an indomitable sustainment of man\'s world in the precise terms of his own special participation in its varying aspects.' },  // 197 · Libra 17
  { image: 'Two men placed under arrest.', interpretation: 'the maximum demand that may be made of any individual for self-consistency, and of the absoluteness of compulsions on human nature to provide a balance between inner and outer capacities.' },  // 198 · Libra 18
  { image: 'A gang of robbers in hiding.', interpretation: 'the periodic exercise of man\'s freedom of spirit and soul in a complete if often unhappy deviation from his normal impulses or attitudes, dramatized here on the side of a practical or everyday self-fulfillment.' },  // 199 · Libra 19
  { image: 'A Jewish rabbi.', interpretation: 'man\'s selfassurance as gained by bringing a deeper understanding to his fellows.' },  // 200 · Libra 20
  { image: 'A crowd upon the beach.', interpretation: 'a complete lack of social sensitiveness.' },  // 201 · Libra 21
  { image: 'A child giving birds a drink at a fountain.', interpretation: 'man\'s uncompromising faith in the friendly relationships characterizing the world at large, or of his naive optimism as he finds that he can take advantage of one or another of life\'s opportunities whenever he chooses to do so.' },  // 202 · Libra 22
  { image: 'Chanticleer.', interpretation: 'the soul\'s ultimate self-realization through a basic integrity of its own insights or judgments, and of the unchallenged acceptance it is able to gain for its particular role in human affairs.' },  // 203 · Libra 23
  { image: 'A third wing on the left side of a butterfly.', interpretation: 'the illimitable potentiality of both man and his world, and of the practical fruits of his efforts whenever he retains his own unconditioned uniqueness of make-up and is alert to whatever opportunities arise in his particular milieu and permit his own special destiny to fulfill itself.' },  // 204 · Libra 24
  { image: 'Information in the symbol of an autumn leaf.', interpretation: 'man\'s stark resourcefulness on the side of imagination or inner experience.' },  // 205 · Libra 25
  { image: 'An eagle and a large white dove turning one into the other.', interpretation: 'exceptional personal endowment on the side of an individual capacity to meet each particular situation, here revealed in a creative or purposive approach to all aspects of human experience.' },  // 206 · Libra 26
  { image: 'An airplane hovering overhead.', interpretation: 'the psychological maturity of man on the ideal side of life, and of the imaginative resourcefulness of character which makes him an immortal being.' },  // 207 · Libra 27
  { image: 'A man in the midst of brightening influences.', interpretation: 'the enduring rewards of life whenever it is taken seriously in its own fundamental terms or accepted with a realization of the underlying friendliness of the world at large.' },  // 208 · Libra 28
  { image: 'Humanity seeking to bridge the span of knowledge.', interpretation: 'man\'s capacity to make himself a very practical instrument for the accumulated experience or perfected wisdom which has built and now supports the world in which he lives.' },  // 209 · Libra 29
  { image: 'Three mounds of knowledge on a philosopher\'s head.', interpretation: 'the eternal fitness of things, as it lies within man\'s power to comprehend this for his own special guidance.' },  // 210 · Libra 30
  { image: 'A sight-seeing bus.', interpretation: 'the individual spirit in its catholicity, and of the naiveté and indomitability of its interest in life as a whole.' },  // 211 · Scorpio 1
  { image: 'A broken bottle and spilled perfume.', interpretation: 'man\'s real power in making his permanent impact on others, dramatized at each moment of issue and crisis by a completeness of the self\'s flow out and into every last ramification of the given experience.' },  // 212 · Scorpio 2
  { image: 'A house-raising.', interpretation: 'the indomitable outreaching of the human spirit on the side of simple cooperations in everyday living, and of the individual\'s realization of his own inherent divinity as he seeks his fulfillment through his fellows.' },  // 213 · Scorpio 3
  { image: 'A youth holding a lighted candle.', interpretation: 'a true contact with inner and transcendental realms of reality, and of the rewards to the spirit which come from a realization of the continuing ties between the least of individuality and universal life as such.' },  // 214 · Scorpio 4
  { image: 'A massive, rocky shore.', interpretation: 'the dependability of the physical universe whenever man holds the center of reality within himself and uses the static constituents in nature as a sustainment for his essentially dynamic being.' },  // 215 · Scorpio 5
  { image: 'A gold rush.', interpretation: 'the exploitation of natural resources through personal initiative or intelligence, and of every individual\'s essential independence of the commonplace limitations or superficial inadequacies of life.' },  // 216 · Scorpio 6
  { image: 'Deep-sea divers.', interpretation: '' },  // 217 · Scorpio 7
  { image: 'The moon shining across a lake.', interpretation: 'the magic on which man always may call in facing any problems of inner or psychological adjustment.' },  // 218 · Scorpio 8
  { image: 'Dental work.', interpretation: 'self-renewal through a continuous and conscientious attention to the needs of the being on all planes of effort, and.of that stewardship of an inner and divine spark through which individuality sustains its spiritual citizenship in the symbolical community of its kind.' },  // 219 · Scorpio 9
  { image: 'A fellowship supper.', interpretation: 'human service on the practical side of everyday reality, and of the need of man for the company of his fellows in every phase of outer existence.' },  // 220 · Scorpio 10
  { image: 'A drowning man rescued.', interpretation: 'the soul\'s personal immortality, and of its unabated eagerness in returning to the various phases of its experience again and again.' },  // 221 · Scorpio 11
  { image: 'An embassy ball.', interpretation: 'human imagination as the most effective corrective for man\'s allegiances, and of the social dramatizations which enable each person to know whether his over-all loyalties are bringing him the self-fulfillment to which he aspires.' },  // 222 · Scorpio 12
  { image: 'An inventor experimenting.', interpretation: 'the joy in effort put forth on the imaginative or intellectual side of life, and of the creative achievement by which the human individual is able to make a special niche for himself in some particular sphere of activity.' },  // 223 · Scorpio 13
  { image: 'Telephone linemen at work.', interpretation: 'the interconnection which links all phases of existence with all others, and of man\'s special genius for expanding the relationship between the most widely separated and distinctive aspects of experience.' },  // 224 · Scorpio 14
  { image: 'Children playing around five mounds of sand.', interpretation: '' },  // 225 · Scorpio 15
  { image: 'A girl\'s face breaking into a smile.', interpretation: 'the need to share any true essence of selfhood, as here brought to an immediate actuality in everyday living.' },  // 226 · Scorpio 16
  { image: 'A woman the father of her own child.', interpretation: 'the eternal conflict between the practical involvements and the ideal potentialities of human nature, as here emphasized in man\'s conscious individuality.' },  // 227 · Scorpio 17
  { image: 'A woods rich in autumn coloring.', interpretation: 'nature\'s high ministry of service to every function and purpose of individual living, and of the varying manifestations of a reality supported and brought to its genuine fruitage by the eternal and illimitable resources on every hand.' },  // 228 · Scorpio 18
  { image: 'A parrot listening and then talking.', interpretation: 'the raw substance of intelligence, and it suggests that conscious existence can be shaped according to any desired lineaments.' },  // 229 · Scorpio 19
  { image: 'A woman drawing two dark curtains aside.', interpretation: 'the enduring values which the average individual visualizes behind the outer facade of everyday existence, and of his desire to penetrate to more worthy dimensions of experience.' },  // 230 · Scorpio 20
  { image: 'Ai soldier derelict in duty.', interpretation: 'the necessary adjustments of life on the side of decisions and consequences, and of the penalties for man\'s lack of discrimination in any given set of circumstances.' },  // 231 · Scorpio 21
  { image: 'Hunters starting out for ducks.', interpretation: 'the simplicity of self-expression and the straightforward honesty of desire which men tend to exhibit from birth in nearly every realm of normal or everyday activity, and of the average individual\'s need for genuine psychological elbowroom in his dealing with the world about him.' },  // 232 · Scorpio 22
  { image: 'A bunny metamorphosed into a fairy.', interpretation: 'the inner or creative values of everyday living, and of the personal or more dynamic meanings with which man may endow the least of the things around him.' },  // 233 · Scorpio 23
  { image: 'Crowds coming down the mountain to listen to one man.', interpretation: 'recognition for intellectual attainment, and of the supremacy of spiritual over other and more tangible forms of authority among men.' },  // 234 · Scorpio 24
  { image: 'An X ray.', interpretation: 'man\'s organic integrity, or of the unvarying structures of nature on which all intelligence depends.' },  // 235 · Scorpio 25
  { image: 'Indians making camp.', interpretation: 'man\'s inexhaustible capacity for self-establishment and for finding everything he needs immediately at hand, as here given emphasis on the practical side.' },  // 236 · Scorpio 26
  { image: 'A military band on the march.', interpretation: 'the human spirit\'s continual desire to avoid everyday trivialities and drabness, ever pressing on toward some goal which can become a basis for a more enduring and individual reality.' },  // 237 · Scorpio 27
  { image: 'The king of the fairies approaching his domain.', interpretation: 'the eternal promise underlying all inner self-realization, since any actual fullness of life is altogether independent of the passing state of affairs in a world of time and space.' },  // 238 · Scorpio 28
  { image: 'An Indian squaw pleading to the chief for the lives of her children.', interpretation: 'the stark sacrifices the self must make in the common interest and of the high responsibilities the group must accept for the welfare of each individual, as these factors together create a functioning society and enable man to control his everyday world.' },  // 239 · Scorpio 29
  { image: 'The Halloween jester.', interpretation: 'a proper informality in the release of the buoyant energies through which an individual gains refreshment, or is freed for the moment from life\'s insistent demand on him that he live according to some ideal beyond his potentiality.' },  // 240 · Scorpio 30
  { image: 'A Grand Army of the Republic campfire.', interpretation: 'man\'s continuing appreciation of every phase of experience that ever has opened up for him, and his desire to live worthily as a basis for every present or future well-being.' },  // 241 · Sagittarius 1
  { image: 'The ocean covered with whitecaps.', interpretation: 'the unending availability of everything ever needed for life and experience, emphasized subjectively through the tireless anticipations of the human soul.' },  // 242 · Sagittarius 2
  { image: 'Two men playing chess.', interpretation: 'the self-confidence and authority which come to man through his refinement of skills and discipline of understanding, and of his capacity for mobilizing every potentiality of self at any point of challenge in events.' },  // 243 · Sagittarius 3
  { image: 'Ai little child learning to walk.', interpretation: 'the maximum possible encouragement of human personality on the practical or objective side, or of life\'s continual stimulus to every potentiality of skill and character.' },  // 244 · Sagittarius 4
  { image: 'An old owl up ina tree.', interpretation: 'the necessary element of steadiness in human affairs, and of the extent to which the demonstrated and widely accepted values of life must have their full and functioning part in the immediate reality with which an individual may be seeking to come to terms.' },  // 245 · Sagittarius 5
  { image: 'A game of cricket.', interpretation: 'man\'s insatiable desire to refine and strengthen every last potentiality of his own personal character and skills, and of his need to gain recognition for his success in this from each area of life in which he finds himself.' },  // 246 · Sagittarius 6
  { image: 'Cupid knocking at the door.', interpretation: 'the unimpeachable resources of life on the side of social self-renewals and psychological self-fulfillment.' },  // 247 · Sagittarius 7
  { image: 'Rocks and things forming therein.', interpretation: 'the necessity that man create his own reality out of the actual situations in which he becomes involved, and that he do so by taking control of the circumstances which provide the matrix for his everyday existence.' },  // 248 · Sagittarius 8
  { image: 'A mother with her children on stairs.', interpretation: 'extreme alertness to the interests and needs of others, and of high competency in pursuing any and all ideal ends in view.' },  // 249 · Sagittarius 9
  { image: 'A golden-haired goddess of opportunily.', interpretation: 'the sure protection afforded every individual who enters experience with a genuine self-expenditure, and of the inevitable good fortune coming to those who refuse to be dependent on encouragement or support from others.' },  // 250 · Sagittarius 10
  { image: 'The lamp of physical enlightenment at the left temple.', interpretation: 'the enlarged understanding which comes from an inner and spiritual outreaching, and of the rewards following on a ceaseless experiment with one or another mode of self-expression.' },  // 251 · Sagittarius 11
  { image: 'A flag that turns into an eagle that crows.', interpretation: 'the balance which every individual must maintain between the established allegiances which create the substance of his conscious selfhood and the idealized ambitions by which he is self-sustained as an identity in his own right.' },  // 252 · Sagittarius 12
  { image: 'A widow\'s past is brought to light.', interpretation: '' },  // 253 · Sagittarius 13
  { image: 'The Pyramids and the Sphinx.', interpretation: 'the ultimate criterion of reality provided by the common or physical world of normal experience, here at the extreme of man\'s enduring works in material substance.' },  // 254 · Sagittarius 14
  { image: 'The ground hog looking for its shadow.', interpretation: 'the creative interest of man in the immediate set or drift of the potentialities on which he must depend.' },  // 255 · Sagittarius 15
  { image: 'Sea gulls watching a ship.', interpretation: 'the spirit\'s demand for its full share in the privileges and rewards of human society, and of the individual\'s realization that his personal interests are served only as he maintains an unceasing vigilance in his own behalf.' },  // 256 · Sagittarius 16
  { image: 'An Easter sunrise service.', interpretation: 'man\'s achievement on the level of spiritual or eternal fellowship with others, here emphasized objectively by the enduring values he is able to dramatize for himself in everyday religious terms.' },  // 257 · Sagittarius 17
  { image: 'Tiny children in sunbonnets.', interpretation: 'man\'s very common self-cloistering on the practical side of experience, or of the individual\'s capacity to give primary and needed attention to his own personal affairs.' },  // 258 · Sagittarius 18
  { image: 'Pelicans moving their habitat.', interpretation: 'the ultimate integrity of individual character, with each particular skill and capacity incorporated in selfhood as a potential of self-competency for subsequent refinement.' },  // 259 · Sagittarius 19
  { image: 'Men cutting through ice.', interpretation: 'the facility with which men organize the processes of nature for the benefit of the community at large.' },  // 260 · Sagittarius 20
  { image: 'A child and a dog with borrowed eyeglasses.', interpretation: 'man\'s unimpeachably universal spirit, and of his realization that there are no absolute lines of demarcation between higher and lower life or between the varying stages of competency to be found in each.' },  // 261 · Sagittarius 21
  { image: 'A Chinese laundry.', interpretation: 'complete self-refinement through the unsuspected or even generally unaccepted activities of the community, and of a consummation of the being through specialized interests which may tend to deny man his more superficial communion with his fellows.' },  // 262 · Sagittarius 22
  { image: 'Immigrants entering.', interpretation: 'opportunity caught and held through its effective recognition in advance, here dramatized by the creative faith of those who risk their well-being in bringing their skills into pioneer areas of self-expression.' },  // 263 · Sagittarius 23
  { image: 'A bluebird standing at the door of the house.', interpretation: 'the persisting imminence of real rewards in experience, and of an ever-immediate danger of failing to see or welcome them.' },  // 264 · Sagittarius 24
  { image: 'A chubby boy on a hobbyhorse.', interpretation: 'the ambition by which man ultimately manages to leave his immortal stamp on the world around him, here dramatized in his desire for a fullness of living and a perfection of accomplishment.' },  // 265 · Sagittarius 25
  { image: 'A flag-bearer.', interpretation: 'the enduring significance which tends to overshadow the more immediate interests or wholly selfish concerns of man, and the emphasis is on the natural supremacy of common ideals over mere individual ambitions.' },  // 266 · Sagittarius 26
  { image: 'A sculptor.', interpretation: 'creative ability as the manifestation of self-consciousness in its maturity of realization, dramatized by an irresistible desire to endow all life with some enduring potentiality.' },  // 267 · Sagittarius 27
  { image: 'An old bridge over a beautiful stream.', interpretation: 'the eternal stability of the world at large, and of each person\'s ability to preserve its form and function in full accordance with his own convenience.' },  // 268 · Sagittarius 28
  { image: 'A fat boy mowing the lawn.', interpretation: 'the contribution of familiar experience to the refinement of selfhood, given emphasis by the full self-expenditure required for any satisfactory acceptance into a fellowship with others.' },  // 269 · Sagittarius 29
  { image: 'The Pope.', interpretation: 'human excellence on the side of the special values exalted in the various social and political hierarchies of modern civilization, and of man\'s ambition as entirely inadequate except as he is able to meet some exceptional need of everyday experience and so proceed to dramatize whatever abilities he may have developed in climbing to the position in which he finds himself.' },  // 270 · Sagittarius 30
  { image: 'An Indian chief demanding recognition.', interpretation: 'the extreme fidelity of the normal individual to the everyday or accepted values of life, and of his uncompromising inner integrity when it comes to meeting any situation of the moment.' },  // 271 · Capricorn 1
  { image: 'Three stained-glass windows, one damaged by bombardment.', interpretation: 'man\'s illimitable capacity for memorializing his experience by the record he leaves in history, and of the necessity that he protect his handiwork from the superficial destructiveness of a life without vision or pride.' },  // 272 · Capricorn 2
  { image: 'The human soul receptive to growth and understanding.', interpretation: 'mankind\'s fundamentally naive capacity for experience, and of every individual\'s equally fundamental dependence on the understanding and support of fellow participants in each moment of self-discovery.' },  // 273 · Capricorn 3
  { image: 'A party entering a large canoe.', interpretation: 'man\'s necessary adjustment of the practical details in his immediate environment as a preliminary to any personal participation in experience, and of his greater concern with these at times than with the real ends in view.' },  // 274 · Capricorn 4
  { image: 'Indians rowing a canoe and dancing a war dance.', interpretation: 'the irresistible impulse to action inherent in the very fact of conscious being, and of the powers of accomplishment brought to their personal focus as some pattern of motives takes form on the subjective side of things.' },  // 275 · Capricorn 5
  { image: 'A dark archway and ten logs at the bottom.', interpretation: 'the illimitable resources of self in preserving its own integrity through the varying fortunes of everyday living, and of the satisfaction anyone may know through a conscious direction of his own destiny.' },  // 276 · Capricorn 6
  { image: 'A veiled prophet of power.', interpretation: 'nature\'s illimitable potentialities on the side of her readiness to meet the physical and psychological demands of man, and of the necessity that he exercise his mastery of natural forces as a basis for his self-assurance in meeting everyday strain and turmoil.' },  // 277 · Capricorn 7
  { image: 'Birds in the house singing happily.', interpretation: 'the descent of spirit or intelligence into every last ramification of everyday reality, and of man\'s self-fulfillment as he is successful in shaping circumstances or precipitating events so that they become the ultimate and outward revelation of that higher vision by which he continues to be himself at core.' },  // 278 · Capricorn 8
  { image: 'An angel carrying a harp.', interpretation: 'the eternal and unabated interest of the human spirit in the simple potentialities of experience, and of the unconditioned enthusiasm of all human motives in their original inception.' },  // 279 · Capricorn 9
  { image: 'An albatross feeding from the hand.', interpretation: 'man\'s basic self-justification on the practical or commonplace side, and of his complete dependence on the cooperation of the world at large for any actuality of personal experience.' },  // 280 · Capricorn 10
  { image: 'A large group of pheasants.', interpretation: 'the social ritualization by which man\'s everyday personality is able to maintain and refine its particular characteristics, and of the common expression of self through which life endows each individual with his fundamental inner certainty and his convenient outer reality.' },  // 281 · Capricorn 11
  { image: 'A student of nature lecturing.', interpretation: 'the wide ramification in experience by which man achieves his greater opportunities, emphasized on the vicarious or intellectual side as he participates in events and shares meanings through the mind\'s eye alone.' },  // 282 · Capricorn 12
  { image: 'A fire worshiper.', interpretation: 'man\'s inner strength through his realization of an inviolable tie with the creative power of the universe itself, dramatized by his continual outreach to the divine in a spiritualizing of his aspiration and a dedication of his talents and possessions to the over-all reality.' },  // 283 · Capricorn 13
  { image: 'An ancient bas-relief carved in granite.', interpretation: 'the immeasurable potentiality of the present moment as a recurrent manifestation of all that ever has been or that ever can be, and of the ability of man to capitalize on opportunities thus brought to focus in himself and his world at large again and again.' },  // 284 · Capricorn 14
  { image: 'Many toys in the children\'s ward of a hospital.', interpretation: 'the inescapable richness of life in any normal manifestation of itself, here given emphasis through its ample rewards on the social and ideal side.' },  // 285 · Capricorn 15
  { image: 'Boys and girls in gymnasium suits.', interpretation: 'practical experience as at root a matter of developing self-competency, and of life as a never-ending adjustment of ideals and motives to the everyday potentials of human society.' },  // 286 · Capricorn 16
  { image: 'A girl surreptitiously bathing in the nude.', interpretation: 'the irresistible desire of all life to strip back to essentials, and to gain self-renewal by some immediate and close intimacy with the accepted roots of all-being.' },  // 287 · Capricorn 17
  { image: 'The Union Jack.', interpretation: 'the maximum protection which life at large will provide for the individual in general, here given emphasis on the social or political side.' },  // 288 · Capricorn 18
  { image: 'A child of about five with a huge shopping bag.', interpretation: 'the spiritual stewardship of man as expressed in his inherent sense of responsibility for the welfare of others, and in his desire to serve his community to the extreme of his particular range of skills.' },  // 289 · Capricorn 19
  { image: 'A hidden choir singing.', interpretation: 'the eternal music of the spheres, and is an emphasis on the ideality of experience as at root a symphony of cosmic reconciliations.' },  // 290 · Capricorn 20
  { image: 'A relay race.', interpretation: 'an inevitable culmination for group opportunity, and of a continual enhancement of the individual\'s skills and talents through his thoroughgoing co-operation with others in some vital phase of experience.' },  // 291 · Capricorn 21
  { image: 'A general accepting defeat gracefully.', interpretation: 'the immediate opportunism by which the human will develops its real power, and of its underlying and uncompromising loyalty to the long-range ends in view.' },  // 292 · Capricorn 22
  { image: 'Two awards for bravery in war.', interpretation: 'man\'s resourcefulness in developing new areas of experience on the practical side, and of his genius for dramatizing the fruits of an everyday aliveness and thereby stimulating a broadened self-expenditure.' },  // 293 · Capricorn 23
  { image: 'A woman entering a convent.', interpretation: 'the soul\'s characteristic dependence on some deepstirring challenge to its potentialities, and of the fact that life can have no satisfaction for the individual unless he is able to develop and maintain some enduring allegiance of an overall significance.' },  // 294 · Capricorn 24
  { image: 'An oriental-rug dealer.', interpretation: 'the irrevocability of man\'s obligation to the reality of which he is a part, with the emphasis on his accumulated knowledge or acquired skills as an indication of his enduring competency on the more immediate or practical side.' },  // 295 · Capricorn 25
  { image: 'A water sprite.', interpretation: 'a pure mastery of experience in its inner or spiritual aspect, and of the possession of every richness of outer reality in a highly imaginative or personal form.' },  // 296 · Capricorn 26
  { image: 'A mountain pilgrimage.', interpretation: 'a pyramiding reality on the side of inner or spiritual realization in a complete harmony of all the ideals and values ever developed by man.' },  // 297 · Capricorn 27
  { image: 'A large aviary.', interpretation: 'the ramifying differentiation of interest to be found in the many areas of normal life, and of man\'s gift for bringing any one special line of effort to the immediate services of any other.' },  // 298 · Capricorn 28
  { image: 'A woman reading tea leaves.', interpretation: 'man\'s persistent desire to establish conscious relationship with an invisible world of over-reality, given an emphasis here on the side of outer or everyday self-encouragement.' },  // 299 · Capricorn 29
  { image: 'A secret business conference.', interpretation: 'the momentary background in human relations as essentially the product of current activities and attitudes, and of a determination to capitalize on any given situation through effective allegiances among the principal personalities involved.' },  // 300 · Capricorn 30
  { image: 'An old adobe mission.', interpretation: 'everlasting sustainment, and of the necessity for both an over-all orientation and an underlying stability in all personal existence.' },  // 301 · Aquarius 1
  { image: 'An unexpected thunderstorm.', interpretation: 'nature\'s potentialities as they lie beyond any individual control, as well as of the tendency of all things to come to some dramatic head in either physical or psychological terms.' },  // 302 · Aquarius 2
  { image: 'A deserter from the navy.', interpretation: 'human independence carried to a point of extreme rebellion against things as they are, here emphasized in a disregard of all consequences for the sake cf an immediate liberation of the spirit. here is a demand for a more rewarding expression of individuality, and the reversed symbolism suggests that any late acceptance of full and personal responsibility for life is better than none at all.' },  // 303 · Aquarius 3
  { image: 'A Hindu healer.', interpretation: 'self-assertion at a point of effective impact on the world, dramatized here on the side of an inner and transcendental reality.' },  // 304 · Aquarius 4
  { image: 'A council of ancestors.', interpretation: '' },  // 305 · Aquarius 5
  { image: 'A masked figure performs ritualistic acts.', interpretation: '' },  // 306 · Aquarius 6
  { image: 'A child born of an eggshell.', interpretation: 'the infinite regression in all personal reality, not as a fact of some mysterious loss of self either in source or in final dissolution but as a demonstration of the illimitable potentialities to be found in each immediate moment of self-realization.' },  // 307 · Aquarius 7
  { image: 'Beautifully gowned wax figures.', interpretation: 'the ineradicable vanity of the human spirit as it gathers strength not only from the finery it wears but from a superficial display of woman\'s form and man\'s reputation, here emphasized through personal idealizations.' },  // 308 · Aquarius 8
  { image: 'A flag turned into an eagle.', interpretation: 'man\'s inexhaustibly fertile imagination or genius for significant self-representation, and of his capacity for rising to every situation in the terms of its most rewarding potentials.' },  // 309 · Aquarius 9
  { image: 'A popularity that proves ephemeral.', interpretation: 'the eternal challenge which comes to an individual at every point of climax in his experience, and of the swing of the pendulum between an endorsement and a repudiation of his efforts by his social group.' },  // 310 · Aquarius 10
  { image: 'Man tête-à-tête with his inspiration.', interpretation: 'satisfaction in the transcendental experiences of selfhood, and of a new realization that each individual lives in a consistent intimacy with spiritual verities of every sort and on every hand.' },  // 311 · Aquarius 11
  { image: 'People on stairs graduated upwards.', interpretation: 'the common enhancement of individual experience on the side of its inner gratification, and of the inherent differences among human kind which enable man to share any endeavor with his fellows whenever they prove either more or less competent than himself.' },  // 312 · Aquarius 12
  { image: 'A barometer.', interpretation: 'man\'s great love for living his experience in advance, and of his gift for meeting every possible contingency by an effective estimation of his own potentials.' },  // 313 · Aquarius 13
  { image: 'A train entering a tunnel.', interpretation: 'life\'s normal expectation in the performance of community services or in the refinement of social divisions of labor, and of the utterly natural participation of self in its more impersonal relationships with others.' },  // 314 · Aquarius 14
  { image: 'Two lovebirds sitting on a fence.', interpretation: 'nature\'s delight in exhibiting the fruits of simple self-fulfillment, dramatized most effectively as a natural consummation of a shared richness or tenderness in human personality.' },  // 315 · Aquarius 15
  { image: 'A big-business man at his desk.', interpretation: 'personal stability through organizational powers, emphasized in terms of an efficient participation in everyday affairs.' },  // 316 · Aquarius 16
  { image: 'A watchdog standing guard.', interpretation: 'the inviolability of experience as dramatized for each individual through the social sanctions and legal rights on which he may count in his own personal affairs.' },  // 317 · Aquarius 17
  { image: 'A man unmasked.', interpretation: 'the human mind\'s illimitable power for penetrating into the deeper stirrings and underlying motivations of human nature, and of a very modern determination to gain a scientific mastery of every psychological process.' },  // 318 · Aquarius 18
  { image: 'A forest fire quenched.', interpretation: 'regenerative relaxation after extraordinary effort, and of man\'s exceptional capacity for achievement through the whole-giving of himself in an emergency.' },  // 319 · Aquarius 19
  { image: 'A big white dove, a message bearer.', interpretation: 'man\'s recognition of a transcendental or superior wisdom from which he may always receive his inspiration and assurance, emphasized here by his inner faith and his selfstrengthening through an ever-constructive attitude of mind.' },  // 320 · Aquarius 20
  { image: 'A woman disappointed and disillusioned.', interpretation: 'the inevitable distress of the human soul whenever it seeks any enduring sustainment from elements without anchorage in its own nature, dramatized in the negative symbolism by the futility of its attempted fulfillment through a capitalization on purely physical assets of self.' },  // 321 · Aquarius 21
  { image: 'A rug placed on a floor for children to play.', interpretation: 'the unlimited service of life at large to the special requirements of an individual\'s comfort or everyday convenience.' },  // 322 · Aquarius 22
  { image: 'A big bear sitting down and waving all tts paws.', interpretation: 'man\'s absolute mastery of his own lower nature, and of his ability to bring every function of life to a high personal fulfillment.' },  // 323 · Aquarius 23
  { image: 'A man turning his back on his passions and teaching from his experience.', interpretation: 'the complete self-obsession which human individuality may exhibit, emphasized here on the side of a sensitiveness to the world and its exactions.' },  // 324 · Aquarius 24
  { image: 'A butterfly with the right wing more perfectly formed.', interpretation: 'man\'s capacity to overcome any handicap imposed on him by the abnormalities which at times become an inevitable part of his own nature, and of his underlying stamina or psychological integrity.' },  // 325 · Aquarius 25
  { image: 'A hydrometer.', interpretation: 'the powers of immediate analysis which enable man to achieve his commonplace or practical goals.' },  // 326 · Aquarius 26
  { image: 'An ancient pottery bowl filled with violets.', interpretation: 'the permanence or changelessness of the real as an ultimate assurance to the human heart.' },  // 327 · Aquarius 27
  { image: 'A tree felled and sawed.', interpretation: 'the employment of a lesser reality for the development and sustainment of a greater, and of the individual\'s ability in a crisis to center his attention on the pressing functions and necessities of a very practical well-being.' },  // 328 · Aquarius 28
  { image: 'Butterfly emerging from chrysalis.', interpretation: 'humanity\'s insatiable appetite for experience on the side of an intellectual self-assurance, and of the nascent eagerness of the conscious self for a complete or effective grasp of all possible knowledge.' },  // 329 · Aquarius 29
  { image: 'The field of Ardath in bloom.', interpretation: 'the spiritual integrity of nature herself, dramatized by Marie Corelli\'s mystic meadow of ancient Babylon as an ageless and special challenge to modern life.' },  // 330 · Aquarius 30
  { image: 'A public market.', interpretation: 'full maturity in man\'s social estate, with an emphasis on the group integrity which facilitates the development of each individual in his own special pattern.' },  // 331 · Pisces 1
  { image: 'A squirrel hiding from hunters.', interpretation: 'the conscious conservatism through which man preserves his more enduring values, here emphasized by an uncompromising loyalty to his own self-interest.' },  // 332 · Pisces 2
  { image: 'A petrified forest.', interpretation: 'the absolute certainty which any individual may develop in the terms of his conscious knowledge, and of the power in human character which becomes the hallmark of his intellectual orientation.' },  // 333 · Pisces 3
  { image: 'Heavy traffic ona narrow isthmus.', interpretation: 'the ultimate illimitability of human relationships, dramatized here in the more personal and ever-ramifying environment of everyday affairs.' },  // 334 · Pisces 4
  { image: 'A church bazaar.', interpretation: 'the instinctive loyalties of life as manifest in community institutions, and of man\'s ability to capitalize on the enduring allegiances he develops among his kind.' },  // 335 · Pisces 5
  { image: 'Officers on dress parade.', interpretation: 'a cyclic and necessary intensification of any personal being, as emphasized on the side of ritualized or ideal experience.' },  // 336 · Pisces 6
  { image: 'A cross lying on rocks.', interpretation: 'withdrawal from reality in one aspect as means for regrasping it in another, here dramatized by a wholly unnecessary acceptance of the world\'s common repudiation or neglect of an individual\'s higher ideals.' },  // 337 · Pisces 7
  { image: 'A girl blowing a bugle.', interpretation: 'the selfperfecting required for the many different forms of man\'s participation in the experience of his fellows, illustrated here in his successful achievement and discharge of group responsibility.' },  // 338 · Pisces 8
  { image: 'A jockey.', interpretation: 'the eagerness for life an individual must show in any true revelation of himself, and of the concern he must have for the struggles and competitions of everyday experience.' },  // 339 · Pisces 9
  { image: 'An aviator in the clouds.', interpretation: 'man\'s transcendental powers of comprehension, emphasized here in his exploratory genius and his gift for creating the endless hypotheses he needs for solving the problems of a modern world.' },  // 340 · Pisces 10
  { image: 'Men seeking illumination.', interpretation: 'the immortality of man as dramatized in some form of an apostolic succession, or a living tradition of spiritual achievement.' },  // 341 · Pisces 11
  { image: 'An examination of initiates.', interpretation: 'life\'s demand that man continue at all times to prove himself in full accordance with the claims he has made for himself, emphasized here on the side of his ideals and spiritual aspiration.' },  // 342 · Pisces 12
  { image: 'A sword ina museum.', interpretation: 'the real weight of human personality, emphasized here by the surviving influence of great figures out of the past.' },  // 343 · Pisces 13
  { image: 'A lady in fox fur.', interpretation: 'the evereffective dynamic with which everyday custom endows mankind, dramatized here by an individual\'s desire to be in style and to express opinions of momentary weight.' },  // 344 · Pisces 14
  { image: 'An officer preparing to drill his men.', interpretation: 'man\'s self-betraying desire for a hierarchy of allegiances in which he can lose himself, evident on the side of the superficial life of everyday and its dismissal of all responsibility of consequence.' },  // 345 · Pisces 15
  { image: 'The flow of inspiration.', interpretation: 'the spiritual power which the development of civilization has brought to a point of practical potentiality, and on which each person may draw in meeting any or all critical issues of everyday living.' },  // 346 · Pisces 16
  { image: 'An Easter promenade.', interpretation: 'that constant expansion of self and experience which characterizes reality on its conscious levels, emphasized here on the side of humanity\'s utterly individualistic self-expression.' },  // 347 · Pisces 17
  { image: 'A gigantic tent.', interpretation: 'the completeness with which man is able to see his experience both steadily and whole, dramatized here by the circus as representing an utterly naive intensification of self-consciousness.' },  // 348 · Pisces 18
  { image: 'A master instructing his pupil.', interpretation: 'the unlimited potentiality of existence in any larger dimension, and of the demand of human intelligence for the self-refinement and self-orientation by which a greater understanding is possible.' },  // 349 · Pisces 19
  { image: 'A table set for an evening meal.', interpretation: 'nature\'s prodigality as revealed through the normal satisfactions for which modern man seldom has to exert himself, and as these take on significance through his instinct for finding every phase of reality a special revelation of his own potentials.' },  // 350 · Pisces 20
  { image: 'A little white lamb, a child and a Chinese servant.', interpretation: '' },  // 351 · Pisces 21
  { image: 'A man bringing down the new law from Sinai.', interpretation: '' },  // 352 · Pisces 22
  { image: 'Spiritist phenomena.', interpretation: 'the organic integrity of the world at large, evident here in man\'s facility for actual and conscious co-operation with the potentials of an immortal reality.' },  // 353 · Pisces 23
  { image: 'An inhabited island.', interpretation: 'the selfadequacy of experience on the objective side of everyday reality, and of man\'s gift for the organization of his own private world in any area of his special interest.' },  // 354 · Pisces 24
  { image: 'The purging of the priesthood.', interpretation: 'the inevitable judgment which life must pronounce on itself, and of the sure penalties that await whatever may fail to prove its worth.' },  // 355 · Pisces 25
  { image: 'A new moon that divides its influences.', interpretation: 'universal initiative as a basic dynamic in any personal scheme of things, and it reveals itself most simply in man\'s instinctive and often blind outreach to the reality in which he participates.' },  // 356 · Pisces 26
  { image: 'A harvest moon.', interpretation: 'life\'s moments of culmination as the threshold of new achievement rather than as any canceling out of experience in the given aspect, and it emphasizes the fact that nature in her immeasurable prodigality is forever showering man with the products of her untiring creativeness.' },  // 357 · Pisces 27
  { image: 'A fertile garden under the full moon.', interpretation: 'a simple satisfaction through outer rather than inner manifestations of reality, or of a normal self-dedication to purely conventional accomplishment.' },  // 358 · Pisces 28
  { image: 'A prism.', interpretation: 'the world\'s stability, and of the refusal of nature to change any aspect of herself unnecessarily.' },  // 359 · Pisces 29
  { image: 'The Great Stone Face.', interpretation: 'human responsibility as an immortality of the soul, and of a way of living which has become a continual manifestation of its ideal and so a constant dramatization of its self-discovery to others as an encouragement to them in their own alignment to eternal reality.' },  // 360 · Pisces 30
] as const
