-- ============================================================
-- 0015_month_briefs.sql
--
-- Personalised monthly brief generated by Claude. One row per
-- (user, plan_year, month). Generated lazily on first /year?view=month
-- visit, cached forever after (regen is a separate explicit action).
--
-- Distinct from blueprints.months[].energyArc (a single tagline). This is
-- a 3–4 paragraph letter grounding the user in the month given their
-- natal chart, the month's transits, their year vision, journal patterns,
-- and Oracle captures marked for planner context.
--
-- See lib/ai/month-brief-generator.ts for the generation pipeline.
-- ============================================================

CREATE TABLE IF NOT EXISTS month_briefs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  blueprint_id UUID REFERENCES blueprints(id) ON DELETE SET NULL,
  plan_year INTEGER NOT NULL,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  brief_text TEXT NOT NULL,
  model_used TEXT NOT NULL DEFAULT 'claude-sonnet-4-6',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT month_briefs_unique_per_user UNIQUE (user_id, plan_year, month)
);

CREATE INDEX IF NOT EXISTS month_briefs_user_year_idx
  ON month_briefs(user_id, plan_year);

ALTER TABLE month_briefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "own_month_briefs" ON month_briefs FOR ALL
  USING (user_id = (
    SELECT id FROM user_profiles
    WHERE clerk_user_id = app_current_clerk_user_id()
  ))
  WITH CHECK (user_id = (
    SELECT id FROM user_profiles
    WHERE clerk_user_id = app_current_clerk_user_id()
  ));
